### ISSUE TITLE
[PS UI] Toast update

### ISSUE THREAD

**Issue by Cal-L** [MetaMask/design-tokens#139]
### **Description**

- [ ] Create _base component for toast Container
- [ ] Creat _base component for toast content

### **References**

Figma https://www.figma.com/file/HKpPKij9V3TpsyMV1TpV7C/Design-System-2.0?node-id=2574%3A18374

**Comment by Akatori-Design** [comment]
done
Figma : https://www.figma.com/file/HKpPKij9V3TpsyMV1TpV7C/DS-Components?node-id=8013%3A24678
