### ISSUE TITLE
Typography documentation page in notion

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/design-tokens#151]
### **Description**
Currently our typography page in notion just displays a table of sizes. Update the [typography page in notion](https://www.notion.so/Typography-033c6721b8004b4283777595c9917b3c) so it is a little more designer friendly.

### **Technical Details**

- Add font family section where brand fonts can be downloaded
- Add description explaining the 2 different typography tables
- Add link to design token storybook

### **Acceptance Criteria**

- Be able to download brand fonts from typography page
- Has font family section
- Has scale section explaining large screen and small screen scale
- Has links to figma 
- Has links to design tokens stoybook

### **References**

- [design tokens typography page](https://metamask.github.io/design-tokens/?path=/docs/typography-typography--font-family)

Example typography pages
https://spectrum.adobe.com/page/typography/
https://atlassian.design/foundations/typography/
https://palette.artsy.net/atoms/typography/
https://rei.github.io/rei-cedar-docs/foundation/typography/
https://m3.material.io/styles/typography/overview

**Comment by Akatori-Design** [comment]
https://www.notion.so/Typography-033c6721b8004b4283777595c9917b3c
