### ISSUE TITLE
Update Figma library covers

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/design-tokens#154]
### **Description**

Our covers for our figma libraries could be improved 

### **Technical Details**

- Simplify text to just the library name
- Use same font size across the board
- Update all libraries to include defining graphic or symbol

### **Acceptance Criteria**

- All covers are easily read and do not contain any hard to read test
- All covers use the same template, font-sizes and layout
- All covers contain a defining graphic
- All covers contain the library name and that library name is easy to read and clearly understood

### **References**

Our covers
<img width="1440" alt="Screen Shot 2022-05-26 at 12 14 56 PM" src="https://user-images.githubusercontent.com/8112138/170582905-8d4b9a7b-2590-44d3-b022-7d9fcca483fa.png">

vs Polaris figma covers
<img width="721" alt="Screen Shot 2022-05-26 at 12 18 25 PM" src="https://user-images.githubusercontent.com/8112138/170582933-9cdc4391-95a8-4649-8dd1-ca013d969872.png">

**Comment by Akatori-Design** [comment]
Quick Mock-Up. 
<img width="1121" alt="image" src="https://user-images.githubusercontent.com/55973039/170588482-6254e219-de1f-4aa4-b25b-10fe75cf40b8.png">

**Comment by georgewrmarshall** [comment]
Love the layout! Not sure of the reasoning behind using purple? Can we choose one of the colors in our brand colors?
