### ISSUE TITLE
Figma DS2.0 inconsistencies

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/design-tokens#159]
### **Description**

Noticed some inconsistencies with DS2.0 library that need updating. Mostly around naming conventions. 

- Let's decide on a naming convention and add it to the docs in Notion
- Looks like mostly we are using title case for components e.g. `Avatar With Badge` this aligns with how we will name our React components so I would push for this naming convention
- For variation and property names we use camel case e.g. tokenName in code so we could also adopt this naming convention as well but I'm open to suggestions

- T-shirt sizes should use consistent naming convention we are using lowercase and uppercase.
![Screen Shot 2022-05-30 at 10 42 56 AM](https://user-images.githubusercontent.com/8112138/171040072-1b196a1b-e6d5-4afd-a440-8dcc7c1ab021.png)
![Screen Shot 2022-05-30 at 10 43 15 AM](https://user-images.githubusercontent.com/8112138/171040074-35ec602e-d242-4968-b7a4-445d86cedbae.png)

- Avatar Account doesn't have a defined property name should be "Size"
![Screen Shot 2022-05-30 at 10 45 07 AM](https://user-images.githubusercontent.com/8112138/171040277-bf120354-8d16-4c5e-afa7-870628cc3780.png)

- Inconsistent naming conventions for variation properties "Type" has a capital "T" while "badge" starts with a lowercase. "with Account Avatar" also doesn't seem to follow any standard convention
![Screen Shot 2022-05-30 at 11 04 55 AM](https://user-images.githubusercontent.com/8112138/171042442-3ceaa39a-f289-4cd4-9e07-8a25848db6f7.png)

**Comment by SaraCheikh** [comment]
for color tokens we always use lower case, so I would vote to update our current property and variant names to use lowercase, and use title case for the component name if you all agree

**Comment by georgewrmarshall** [comment]
@SaraCheikh that sounds good to me!
