### ISSUE TITLE
Icon Wrapper educational demo 

### ISSUE THREAD

**Issue by SaraCheikh** [MetaMask/design-tokens#161]
### **Description**

create a Demo Video about the Icon Wrapper component and how to use it.

### **Technical Details**

Quick walkthrough about:

-the problem that Icon Wrapper solves
-Other wrong solutions (hiding size options within a component, creating size variants of each icon..)
-What Icon Wrapper solves
-how to use Icon Wrapper
-Add & swap icon instances

### **Acceptance Criteria**

- The demo is clear and consice
- The demo has graphic examples accompanying the explanation. 

### **References**

https://www.figma.com/file/HKpPKij9V3TpsyMV1TpV7C/Design-System-2.0?node-id=3636%3A19602

**Comment by Akatori-Design** [comment]
Done
https://www.notion.so/IconWrapper-component-99a8da2f5b2c4deea57570ea37ff8404
