### ISSUE TITLE
Create checklist for definition of done for Figma component 

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/design-tokens#167]
### **Description**

Create checklist for definition of done for Figma component in the context of project management. This will help us to adopt estimates. Right now we cannot estimate if we don’t know what the definition of done is and how much work will have to go into it.

### **Technical Details**

- Create checklist in notion that we can go through to check if a figma component is complete e.g. docs, variations, component testing etc

### **Acceptance Criteria**

- Guideline document exists in notion and covers all areas that should be checked before a component can be marked as "Done"

### **References**

[DS Sync 6/7/22](https://www.notion.so/6-7-22-d08801ee46da44dc9ebf4e8abf45d4cd)

**Comment by Akatori-Design** [comment]
https://www.notion.so/Status-Guides-Success-Criteria-Figma-work-8284fa2512954403ac41ff863d4640c5
