### ISSUE TITLE
[PS] Figmatize Avatar Icon

### ISSUE THREAD

**Issue by Cal-L** [MetaMask/design-tokens#168]
### **Description**

Componentize Avatar Icon in Figma

### **Technical Details**

- Implementation details
- Insight to what needs to be done
- Etc.

### **Acceptance Criteria**

- Check with product on metrics
- Cases to satisfy
- XYZ should work
- Etc.

### **References**

https://www.figma.com/file/HKpPKij9V3TpsyMV1TpV7C/Components?node-id=4146%3A15578

**Comment by Akatori-Design** [comment]
Done 
https://www.figma.com/file/HKpPKij9V3TpsyMV1TpV7C/DS-Components?node-id=4616%3A15460
