### ISSUE TITLE
Reduce variants of _base / Art (Token)

### ISSUE THREAD

**Issue by SaraCheikh** [MetaMask/design-tokens#177]
### **Description**

We currently have too many options for tokens/networks/Dapp which makes it take designers more time to find the logo they need. We need to know which are the top ~12 most used tokens/dapps/networks for designs in order to narrow down our list. 

### **Technical Details**

- Ask the design team to draw up a list of tokens, dapps, network logos they need. [Slack post with suggestions here](https://consensys.slack.com/archives/G4V2HTG0Y/p1655839299032039)
- **Networks:** `Ethereum`, `Arbitrum One`, `Avalanche`, `BNB Smart Chain`, `Optimism`, `Fantom Opera`, `Polygon`, `Harmony`
- **Tokens:** `ETH`, `DAI`, `USDC`, `MATIC`, `BNB`, `ENS`, `WBTC`, `UNI`, `MKR`, `LINK`, `AST`, `1INCH`, `FTM`, `stETH` , `MANA`
- ~12 unique options total? That way we can stress test designs with scrolling, etc. and still have it be realistic for a prototype. - Jake
- Also makes sense to include at least one with a white background and one with a dark background to make sure styling works in both light/dark mode.

### **References**
Figma: https://www.figma.com/file/HKpPKij9V3TpsyMV1TpV7C/DS-Components?node-id=1913%3A10499

[Slack thread](https://consensys.slack.com/archives/G4V2HTG0Y/p1655839299032039)

**Comment by Akatori-Design** [comment]
Reduced
https://www.figma.com/file/HKpPKij9V3TpsyMV1TpV7C/DS-Components?node-id=1913%3A10499
