### ISSUE TITLE
[Ext Nav] Componentize Input Text

### ISSUE THREAD

**Issue by SaraCheikh** [MetaMask/design-tokens#186]
### **Description**

Create a Figma component for Input Text (EXTENSION AND MOBILE).
Input text allow users to input custom text entries. Various options can be shown with the field (placeholder) to communicate the input requirements.

### **Technical Details**

- Create component with mobile and extension variants
- Create variant: label=true/false
- Create variant: help text=true/false
-Create states: Default, hover, focused, filled, disabled

FOR CONTENT:
-Create Inner components:
1._input label
2. _input text with variants: placeholder, typing, filled, secure (for password)
2._input content with variants: default (no icon), left icon, right icon, both icons
3._input help text with variants: default (hint), error
- Guide (Use Case): Help text, validation&error, placeholder, use of icons
- Guide (Use Case) : Option text overflow handling

### **Spec Acceptance Criteria**

- [ ]  Guide has three sections : Anatomy, Dimension, Use Cases. 
- [ ]  Guide’s anatomy contains all necessary component references & links.
- [ ]  Each visual variants ( types, states) have a visual representation, so dev can inspect.
- [ ]  Visual references have correct tokens & styles applied (color, shadow, text).
- [ ]  Component is added to Notion table with matching name, with Figma link.
- [ ]  Resolve old/outstanding comments.

### **Design Components Acceptance Critera**

- [ ]  All Figma components & Boards have consistent & correct Namings
- [ ] (Component Naming System : https://www.notion.so/Component-Naming-System-Draft-6d59eb23d42b483f9f4648506fdb1c29)

- [ ]  Components have necessary variants with consistent naming, and clear labeling.

- [ ]  Components have correct Design Tokens assigned: Color, typography, shadows and spacing.

- [ ]  Components are responsive with text overflow handled.

- [ ]  Components are tested in a prototype and viewed in its respective context (mobile or extension)

- [ ]  Resolve old/outstanding comments.

- [ ]  Component is added to Notion table with status set to “ Figma Done”, and has a Figma link.

 Add update details to the “Upcoming” [release note.](https://www.notion.so/Release-Note-73032fd2ac87466bb727fd54544ab601)

### **References of other DS**

- https://carbondesignsystem.com/components/text-input/usage
- https://spectrum.adobe.com/page/text-field/
- https://material.io/components/text-fields#anatomy

**Comment by Akatori-Design** [comment]
Text Field : https://www.figma.com/file/HKpPKij9V3TpsyMV1TpV7C/DS-Components?node-id=7267%3A27839
