### ISSUE TITLE
[Ext Nav] Componentize Input Search 

### ISSUE THREAD

**Issue by SaraCheikh** [MetaMask/design-tokens#187]
### **Description**

Create a Figma component for Input Search (MOBILE AND EXTENSION). Input Search allows users to quickly find app content to import a token, a network, a setting or search for a Dapp from the browser.

### **Technical Details**

- Create component with Extension and Mobile variants
- Create variants: size=large/small
- Guide (Use Case): behaviour (?): it suggestion list based on app content or previous search?
(token/network/settings search)=suggestion list based on app content
![IMG_9155.PNG](https://images.zenhubusercontent.com/61ef00ec5db2d7c84498dc72/f3572fdf-e981-4202-8a46-e4c8a31bdaa3)![Screenshot 2022-07-04 at 16.22.47.png](https://images.zenhubusercontent.com/61ef00ec5db2d7c84498dc72/c93f2f9b-ee7c-46ba-89e9-b8e0194cbfd9)

(Browser search):suggestion list based on previous search

![IMG_9156.PNG](https://images.zenhubusercontent.com/61ef00ec5db2d7c84498dc72/bdb04c2a-c194-42fd-8bec-308ce063c53c)

- Guide (Use Case) : Option text overflow handling

### ** Spec Acceptance Criteria**

- [ ]  Guide has three sections : Anatomy, Dimension, Use Cases.
- [ ]  Guide’s anatomy contains all necessary component references & links.
- [ ]  Each visual variants ( types, states) have a visual representation, so dev can inspect.
- [ ]  Visual references have correct tokens & styles applied (color, shadow, text).
- [ ]  Component is added to Notion table with matching name, with Figma link.
- [ ]  Resolve old/outstanding comments.

### **Design Component Acceptance Criteria**

 All Figma components & Boards have consistent & correct Namings
(Component Naming System : https://www.notion.so/Component-Naming-System-Draft-6d59eb23d42b483f9f4648506fdb1c29)

 Components have necessary variants with consistent naming, and clear labeling.

 Components have correct Design Tokens assigned: Color, typography, shadows and spacing.

 Components are responsive with text overflow handled.

 Components are tested in a prototype and viewed in its respective context (mobile or extension)

 Resolve old/outstanding comments.

 Component is added to Notion table with status set to “ Figma Done”, and has a Figma link.

 Add update details to the “Upcoming” [release note.](https://www.notion.so/Release-Note-73032fd2ac87466bb727fd54544ab601)

### **References of other DS**

https://carbondesignsystem.com/components/search/usage#variants
https://material.io/design/navigation/search.html
https://polaris.shopify.com/components/autocomplete

**Comment by Akatori-Design** [comment]
https://www.figma.com/file/HKpPKij9V3TpsyMV1TpV7C/DS-Components?node-id=7267%3A28687
