### ISSUE TITLE
[Ext Nav] Create base component for Input

### ISSUE THREAD

**Issue by SaraCheikh** [MetaMask/design-tokens#189]
### **Description**

Create a base component for input (Extension and mobile). 
Inputs let users enter and edit text.

### **Technical Details**

- Create variants for search and text (?)
- Create variants for Extension and mobile 
-Use placeholder component for content

Guide (Use Case): Usage 

### **Spec Acceptance Criteria**

- [ ]  Guide has three sections : Anatomy, Dimension, Use Cases.
- [ ]  Guide’s anatomy contains all necessary component references & links.
- [ ]  Each visual variants ( types, states) have a visual representation, so dev can inspect.
- [ ]  Visual references have correct tokens & styles applied (color, shadow, text).
- [ ]  Component is added to Notion table with matching name, with Figma link.
- [ ]  Resolve old/outstanding comments.

### **Design Components Acceptance Critera**

- [ ]  Guide has three sections : Anatomy, Dimension, Use Cases.
- [ ]  Guide’s anatomy contains all necessary component references & links.
- [ ]  Each visual variants ( types, states) have a visual representation, so dev can inspect.
- [ ]  Visual references have correct tokens & styles applied (color, shadow, text).
- [ ]  Component is added to Notion table with matching name, with Figma link.
- [ ]  Resolve old/outstanding comments.

### **Reference of other DS**
https://www.duetds.com/components/input/

**Comment by Akatori-Design** [comment]
Text Field Base : Text Field Base : https://www.figma.com/file/HKpPKij9V3TpsyMV1TpV7C/DS-Components?node-id=1244%3A11663
