### ISSUE TITLE
[GF UI] Create Accordion component

### ISSUE THREAD

**Issue by SaraCheikh** [MetaMask/design-tokens#198]
### **Description**

Create component for Accordion. An accordion is an all-screensize component used to vertically stack a list of headers that reveal or hide content. 
Componentize for Small Screen then add variants & spec details for Large Screen.

### **Technical Details**

- Variants: expanded=true/false
- Variants (states) : default, hover, pressed
- Guide (use case) : When to use
-- Guide (use case) : States
- Guide (use case) : placement

### **Spec Acceptance Criteria**

- [x]  Guide has three sections : Anatomy, Dimension, Use Cases. ( Can omit boards not applicable)
- [ ]  Guide’s anatomy contains all necessary component references & links.
- [x]  Each visual variants ( types, states) have a visual representation, so dev can inspect.
- [x]  Visual references have correct tokens & styles applied (color, shadow, text).
- [x]  Component is added to Notion table with matching name, with Figma link.
- [ ]  Resolve old/outstanding comments.

### **Design Componet Acceptance Criteria**

- [ ]  All Figma components & Boards have consistent & correct Namings
(Component Naming System : [https://www.notion.so/Component-Naming-System-Draft-6d59eb23d42b483f9f4648506fdb1c29](url)
-
- [x]  Components have necessary variants with consistent naming, and clear labeling.

- [x]  Components have correct Design Tokens assigned: Color, typography, shadows and spacing.

- [x]  Components are responsive with text overflow handled.

- [ ]  Components are tested in a prototype and viewed in its respective context (mobile or extension)

- [ ]  Resolve old/outstanding comments.

- [x]  Component is added to Notion table with status set to “ Figma Done”, and has a Figma link.

- [ ]  Add update details to the “Upcoming” [release note.](https://www.notion.so/Release-Note-73032fd2ac87466bb727fd54544ab601)

### ** DS References**

https://carbondesignsystem.com/components/accordion/usage/#:~:text=The%20accordion%20component%20has%20two,with%20all%20content%20panels%20closed.

https://design-system.service.gov.uk/components/accordion/

https://britishgas.design/docs/components/ns-expander

- Figma Link:

**Comment by Akatori-Design** [comment]
Created guideline & component 
https://www.figma.com/file/HKpPKij9V3TpsyMV1TpV7C/DS-Components?node-id=6126%3A19614
