### ISSUE TITLE
[GF UI] Create Time Estimate component

### ISSUE THREAD

**Issue by SaraCheikh** [MetaMask/design-tokens#199]
### **Description**

Create a Time Estimate component, a molecule formed by a "Tilde" Icon and a typography token. This is a universal component for all screens. Componentize for Small Screen then add variants & spec details for Large Screen.

### **Technical Details**

- Variant: Low=true/false
-Guide (use case)= when to use Low time estimate? 

### **Spec Acceptance Criteria**

- [ ]  Guide has three sections : Anatomy, Dimension, Use Cases
- [ ]  Guide’s anatomy contains all necessary component references & links.
- [ ]  Each visual variants ( types, states) have a visual representation, so dev can inspect.
- [ ]  Visual references have correct tokens & styles applied (color, shadow, text).
- [ ]  Component is added to Notion table with matching name, with Figma link.
- [ ]  Resolve old/outstanding comments.

### **Design Component Acceptance Criteria**

- [ ]  All Figma components & Boards have consistent & correct Namings
- [ ] (Component Naming System : [https://www.notion.so/Component-Naming-System-Draft-6d59eb23d42b483f9f4648506fdb1c29)](url)

- [ ]  Components have necessary variants with consistent naming, and clear labeling.

- [ ]  Components have correct Design Tokens assigned: Color, typography, shadows and spacing.

- [ ]  Components are responsive with text overflow handled.

- [ ]  Components are tested in a prototype and viewed in its respective context (mobile or extension)

- [ ]  Resolve old/outstanding comments.

- [ ]  Component is added to Notion table with status set to “ Figma Done”, and has a Figma link.

- [ ]  Add update details to the “Upcoming” [release note.](https://www.notion.so/Release-Note-73032fd2ac87466bb727fd54544ab601)

### **DS references**

https://www.figma.com/file/aTBlkFLwSzzAXqQG6uf3fV/1559-mobile-exploration-v3?node-id=341%3A3385

-Figma link:

**Comment by Cal-L** [comment]
LGTM!
