### ISSUE TITLE
[GF UI] Create Card component

### ISSUE THREAD

**Issue by SaraCheikh** [MetaMask/design-tokens#200]
### **Description**

Create a component for Card, a container used to organize high-level content. 

### **Technical Details**

-Create a filled container with border and a placeholder component for the content. 
-Guide (use case): when to use a Card component

### **Spec Acceptance Criteria**

- [x]  Guide has three sections : Anatomy, Dimension, Use Cases. ( Can omit boards not applicable)
- [x]  Guide’s anatomy contains all necessary component references & links.
- [x]  Each visual variants ( types, states) have a visual representation, so dev can inspect.
- [x]  Visual references have correct tokens & styles applied (color, shadow, text).
- [x]  Component is added to Notion table with matching name, with Figma link.
- [ ]  Resolve old/outstanding comments.

### **Design Spec Criteria**

 All Figma components & Boards have consistent & correct Namings
(Component Naming System : [https://www.notion.so/Component-Naming-System-Draft-6d59eb23d42b483f9f4648506fdb1c29)](url)

 Components have necessary variants with consistent naming, and clear labeling.

 Components have correct Design Tokens assigned: Color, typography, shadows and spacing.

 Components are responsive with text overflow handled.

 Components are tested in a prototype and viewed in its respective context (mobile or extension)

 Resolve old/outstanding comments.

 Component is added to Notion table with status set to “ Figma Done”, and has a Figma link.

 Add update details to the “Upcoming”[ release note.](https://www.notion.so/Release-Note-73032fd2ac87466bb727fd54544ab601
)
- DS References 

https://www.duetds.com/components/card/
https://orbit.kiwi/components/structure/card/

-Figma Link:

**Comment by Akatori-Design** [comment]
Created guideline & Figma component, and is ready for review
https://www.figma.com/file/HKpPKij9V3TpsyMV1TpV7C/DS-Components?node-id=6345%3A18875
