### ISSUE TITLE
[GF UI] Create Infotip Button component

### ISSUE THREAD

**Issue by SaraCheikh** [MetaMask/design-tokens#202]
### **Description**
Create a Figma component infotip button. (UNIVERSAL COMPONENT)
Infotip is a composite pattern containing a button and an overlay (or tooltip). The button toggles the visibility of the overlay. The overlay contains the info content.

### **Technical Details**

-create infotip button: text+Button Icon (with "info" icon)
-create tooltip component
-variants (states): default, hover, pressed 
-Variant: Large screen=true/false 
-guide (use case): usage
-guide (use case): positioning 

### **Spec Acceptance Criteria**

- [ ]  Guide has three sections : Anatomy, Dimension, Use Cases. ( Can omit boards not applicable)
- [ ]  Guide’s anatomy contains all necessary component references & links.
- [ ]  Each visual variants ( types, states) have a visual representation, so dev can inspect.
- [ ]  Visual references have correct tokens & styles applied (color, shadow, text).
- [ ]  Component is added to Notion table with matching name, with Figma link.
- [ ]  Resolve old/outstanding comments.
 All Figma components & Boards have consistent & correct Namings
(Component Naming System : https://www.notion.so/Component-Naming-System-Draft-6d59eb23d42b483f9f4648506fdb1c29)

### **Design Component Acceptance Criteria**

- [ ]  Components have necessary variants with consistent naming, and clear labeling.
- [ ]  Components have correct Design Tokens assigned: Color, typography, shadows and spacing.
- [ ]  Components are responsive with text overflow handled.
- [ ]  Components are tested in a prototype and viewed in its respective context (mobile or extension)
- [ ]  Resolve old/outstanding comments.
- [ ]  Component is added to Notion table with status set to “ Figma Done”, and has a Figma link.
- [ ]  Add update details to the “Upcoming” release note.

### **References**

- https://ebay.gitbook.io/mindpatterns/disclosure/infotip
-https://clarity.design/documentation/signposts

**Comment by Akatori-Design** [comment]
Created a Data component for figma design
component called "Key + Value"
https://www.figma.com/file/HKpPKij9V3TpsyMV1TpV7C/DS-Components?node-id=9790%3A37079
