### ISSUE TITLE
[GF UI] Create Gas Editor Component

### ISSUE THREAD

**Issue by SaraCheikh** [MetaMask/design-tokens#203]
### **Description**

Create a Figma component for Gas Editor. (UNIVERSAL COMPONENT)
Gas Editor in an organism formed by: Time estimate, Button Icon, Infotip, time estimate, Accordion and text. . Componentize for Small Screen then add variants & spec details for Large Screen. 

### **Technical Details**

-Variants: expanded=true/false
-Variants: type= L1, L2, Generic 
-Use case: text overflow handling

### **Spec Acceptance Criteria**

- [ ]  Guide has three sections : Anatomy, Dimension, Use Cases. ( Can omit boards not applicable)
- [ ]  Guide’s anatomy contains all necessary component references & links.
- [ ]  Each visual variants ( types, states) have a visual representation, so dev can inspect.
- [ ]  Visual references have correct tokens & styles applied (color, shadow, text).
- [ ]  Component is added to Notion table with matching name, with Figma link.
- [ ]  Resolve old/outstanding comments.

### **Design Component Acceptance Criteria**

- [ ]  All Figma components & Boards have consistent & correct Namings
- [ ] (Component Naming System : [https://www.notion.so/Component-Naming-System-Draft-6d59eb23d42b483f9f4648506fdb1c29)](url)
- [ ]  Components have necessary variants with consistent naming, and clear labeling.
- [ ]  Components have correct Design Tokens assigned: Color, typography, shadows and spacing.
- [ ]  Components are responsive with text overflow handled.
- [ ]  Components are tested in a prototype and viewed in its respective context (mobile or extension)
- [ ]  Resolve old/outstanding comments.
- [ ]  Component is added to Notion table with status set to “ Figma Done”, and has a Figma link.
- [ ]  Add update details to the “Upcoming” [release note.](https://www.notion.so/Release-Note-73032fd2ac87466bb727fd54544ab601)

### **References**

Figma link: https://www.figma.com/file/aTBlkFLwSzzAXqQG6uf3fV/1559-mobile-exploration-v3?node-id=441%3A3572

**Comment by Akatori-Design** [comment]
Created, but not a DS building block component. More of a feature component, so has no spec atm.
Figma : https://www.figma.com/file/HKpPKij9V3TpsyMV1TpV7C/DS-Components?node-id=9789%3A32635
