### ISSUE TITLE
Update Button Tertiary

### ISSUE THREAD

**Issue by SaraCheikh** [MetaMask/design-tokens#207]
### **Description**

Update Button Tertiary to be used without padding 

### **Technical Details**

-Create variant of the Button Tertiary component using Button Base Sm
-Name variant: "zero padding"
-Guideline: Usage:

- Button Tertiary:

1. Performs an action, like submitting a form.
2. Button summons a popup or modal, or changes elements of app/extension
3. Label text should be short.
4. can't be used in a paragraph

- Links

1. Text precedes or follows the link.
2. Link redirects to an external site or document.
3. Label text can be longer.
4. can be part of a paragraph

### **Acceptance Criteria**

-https://www.notion.so/Status-Guides-Success-Criteria-Figma-work-8284fa2512954403ac41ff863d4640c5

### **References**

-Figma Link:https://www.figma.com/file/HKpPKij9V3TpsyMV1TpV7C/DS-Components?node-id=2939%3A21698

**Comment by Akatori-Design** [comment]
This was done, but updated again
Now component is renamed to `Button Link`
Variant is renamed to  `auto`
