### ISSUE TITLE
Create Spacing Token

### ISSUE THREAD

**Issue by Akatori-Design** [MetaMask/design-tokens#220]
### **Description**

We don't have spacing token standards as a guide yet. Create in Figma
Reference : https://design.gs.com/foundation/spacing

### **Technical Details**
- Create spacing from 2px - 80px (2,4,8,12,16,24,32,40,48,56,64,72,80)
- Name tokens in format "space-#" 
- Create Figma doc, Notion doc

### **Acceptance Criteria**

- use our documentation template or follow standard format to create figma guide.
- Notion doc "Spacing" is under "Foundation" and has link to the figma guide.

### **References**

Reference : https://design.gs.com/foundation/spacing

**Comment by georgewrmarshall** [comment]
Here is how we could use spacing tokens with Figma tokens
https://www.google.com/search?q=figma+tokens+spacing+tokens&oq=figma+tokens+spacing+tokens&aqs=chrome..69i57.3184j0j1&sourceid=chrome&ie=UTF-8#kpvalbx=_NtIDY7KIM-C90PEP6K-nsAw15

**Comment by Akatori-Design** [comment]
https://www.figma.com/file/GIctVoel8jQYWNuFWaufQh/DS-Spacing

**Comment by Akatori-Design** [comment]
Done : https://www.figma.com/file/GIctVoel8jQYWNuFWaufQh/DS-Spacing?node-id=2%3A2
