### ISSUE TITLE
Add Spacing & Border Radii

### ISSUE THREAD

**Issue by garrettbear** [MetaMask/design-tokens#224]
### **Description**

Add Spacing &  Border Radii Tokens

### **References**

- [Spacing](https://www.figma.com/file/GIctVoel8jQYWNuFWaufQh/DS-Spacing?node-id=2%3A2)
- [Border Radii](https://github.com/MetaMask/metamask-extension/blob/6185cc6e5e7e611ffef7f7c60d926c1a08223a03/ui/components/ui/box/box.scss#L132)

**Comment by Akatori-Design** [comment]
Figma Spacing is "current"
Figma : https://www.figma.com/file/GIctVoel8jQYWNuFWaufQh/DS-Spacing?node-id=2%3A2

**Comment by georgewrmarshall** [comment]
@garrettbear are you still currently working on this? I'm going to move to new issues for the time being
