### ISSUE TITLE
[Figma HK] Replace buttons in X flow

### ISSUE THREAD

**Issue by Cal-L** [MetaMask/design-tokens#245]
### **Description**

Describe the task. What does this aim to solve?

### **Technical Details**

- Implementation details
- Insight to what needs to be done
- Etc.

### **Acceptance Criteria**

- Check with product on metrics
- Cases to satisfy
- XYZ should work
- Etc.

### **References**

- References go here.
- Issue numbers. Links.
- Slack threads.
- Etc.

**Comment by Akatori-Design** [comment]
@Cal-L  I think this might be a ticket u created during a past sprint planning related to b button updates but has no context.

Im moving this back to "New Issue"for now until we know what this ticket is about if that's ok. 

or we can delete it if its dated. 
Thx
