### ISSUE TITLE
Add Sepolia color tokens to light and dark color libraries in Figma

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/design-tokens#251]
### **Description**

Add Sepolia to network colors section in light and dark.

### **Technical Details**

- Already in develop branch just need to pull and update via Figma tokens
- Add documentation and swatch
- Publish library
- Release notification on appropriate Slack channels

### **Acceptance Criteria**

- networks/sepolia/default is available in Figma
- networks/sepolia/inverse is available in Figma

### **References**

- Code equavalent PR https://github.com/MetaMask/design-tokens/pull/243
- Storybook for reference https://metamask.github.io/design-tokens/?path=/story/colors-themecolors--light-theme-colors

<img width="1440" alt="Screen Shot 2022-11-21 at 8 00 13 PM" src="https://user-images.githubusercontent.com/8112138/203218169-7a9caecb-ce0d-416c-879e-ba4f3b5a53a4.png">

**Comment by georgewrmarshall** [comment]
Duplicate https://github.com/MetaMask/design-tokens/issues/252

**Comment by xinnanyemm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Design-System-61e8a2ae77c3a60012e5003c/issues/MetaMask/design-tokens/251?planning-poker) with Zenhub @Akatori-Design @brianacnguyen @garrettbear @georgewrmarshall

**Comment by Akatori-Design** [comment]
Added these new colors in doc & figma style.
`sepolia.default`
`sepolia.inverse`

@georgewrmarshall Requested review for Light Theme & Dark Theme library branches.

Brand : [Figma](https://www.figma.com/file/cBAUPFMnbv6tHR1J8KvBI2/DS-Colors-%2F-Brand?node-id=1502%3A421&t=wzrqdpXoTlLmbgEU-4)
![image.png](https://images.zenhubusercontent.com/62155ddebb3f5e7908734564/fbd24d77-3a4c-4a64-824a-b14cef5ebed6)
Light Theme : [Figma](https://www.figma.com/file/BVMNyPHQ2ysuFwi0uqTphK/adding-sepolia-color?node-id=1823%3A516&t=ttXf00wxISMjijoT-4)
![image.png](https://images.zenhubusercontent.com/62155ddebb3f5e7908734564/76023402-a83c-402d-b768-8b719c5de4cf)
Dark Theme : [Figma](https://www.figma.com/file/hl4aaNtVqFZu3GcXvOFu4E/adding-sepolia-color?node-id=996%3A494&t=NRSmFQuhPkmcNO1D-4)
![image.png](https://images.zenhubusercontent.com/62155ddebb3f5e7908734564/7d174bba-4f4a-4c7f-8073-e0c30b2e8568)
