### ISSUE TITLE
Update Light Colors library with new accessible primary/default and error/default

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/design-tokens#254]
### **Description**

Update Light Colors library with new AA complaint primary/default and error/default.

### **Technical Details**

- Update color styles
- Update documentation
- Release updates 

### **Acceptance Criteria**

- Colors are updates in all components and Figma files to use new AA compliant primary/default and error/default in light mode

### **References**

- https://github.com/MetaMask/design-tokens/issues/253

**Comment by Akatori-Design** [comment]
In Figma, updated two libraries in branch.

1. Brand Color Library
(https://www.figma.com/file/cBAUPFMnbv6tHR1J8KvBI2/branch/mF1cQLmDWDSSdQALMTQCTM/DS-Colors-%2F-Brand?node-id=0%3A1&t=vrSR4YXZSNvmzwQE-1)

Details
Updated Doc & Figma styles for blue500 & red500 as 
Red500 : #D73A49 --> #D73847
Blue500 : #037DD6 --> #0376C9

![image.png](https://images.zenhubusercontent.com/62155ddebb3f5e7908734564/7844901b-a131-4ebe-ad92-b5f6df3282fb)




2. Light Theme Color Library
 (https://www.figma.com/file/kdFzEC7xzSNw7cXteqgzDW/branch/fPda99kjdbcp7iTHX7MxS4/DS--Light-Theme-%2F-Colors-%26-Shadows?t=AFWI50YnBTZgqYkF-1)

Details
Updated Doc & Figma styles for these colors to reflect the new blue500 & red500 color values:
- color / primary-default
- color / primary-muted
- color / error-default
- color / error-muted
- color / info-default
- color / info-muted
- shadow / primary
- shadow / error

Red500 : #D73A49 --> #D73847
Blue500 : #037DD6 --> #0376C9




![image.png](https://images.zenhubusercontent.com/62155ddebb3f5e7908734564/decbd24f-94bd-4054-a0aa-4d7a5e42cf85)
![image.png](https://images.zenhubusercontent.com/62155ddebb3f5e7908734564/0f012edf-e5a6-43bd-9fc8-ff79f44823b2)

**Comment by georgewrmarshall** [comment]
This has been completed
