### ISSUE TITLE
Create optimized image assets for network icons

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/design-tokens#263]
### **Description**

Currently there are inconsistencies and some poor image assets for the networks across the extension. Could we provide a standard set of SVGs for all the networks that we host the image assets for.

<img width="942" alt="Screenshot 2022-12-19 at 11 31 47 AM" src="https://user-images.githubusercontent.com/8112138/208505258-45fef29b-3817-4172-8a62-704485f48ed8.png">
<img width="949" alt="Screenshot 2022-12-19 at 11 32 02 AM" src="https://user-images.githubusercontent.com/8112138/208505265-16eff008-dd2f-4bb3-9c5e-997c6c3bd8cc.png">

### **Technical Details**

- Create optimized quality svg image assets for `Ethereum`, `Polygon`, `Arbitrum One`, `Aurora Mainnet`, `Avalanche Network C-Chain`, `BNB Smart Chain (previously Binance Smart Chain Mainnet)`, `Celo Mainnet`, `Fantom Opera`, `Harmony Mainnet Shard 0`, `Optimism`, `Palm`, `Goerli`, `Sepolia`, `Localhost` (do test networks as well it's easier if they're images for scaling)
- Images should be *square* with a ratio of 1:1 `512px` in size
- Prefixed with `network-`
- Should be all svgs where possible and PNGs if svgs can't be found

### **Acceptance Criteria**

- All network assets exist and meet the above requirements 

### **References**

- https://github.com/MetaMask/metamask-extension/issues/16647

**Comment by brianacnguyen** [comment]
Here's the list of popular networks used by transactions. This can provide a starting point for consolidating a list of network icons
https://mixpanel.com/project/2212883/view/2760759/app/insights#UG3o5jfnCvDU
