### ISSUE TITLE
Standardize spacing tokens

### ISSUE THREAD

**Issue by Cal-L** [MetaMask/design-tokens#3]
### **Description**

Standardize spacing in design system 2.0

### **Technical Details**

- Creation styles of grids
-Publish MVP in Figma (Will only be documentation)
- Get other designers to play around with it + Feedback

### **Reference**

-Figma link: https://www.figma.com/file/HKpPKij9V3TpsyMV1TpV7C/Design-System-2.0?node-id=9%3A253

**Comment by Cal-L** [comment]
Can we attach Figma link to this?

**Comment by georgewrmarshall** [comment]
Figma link in description https://www.figma.com/file/HKpPKij9V3TpsyMV1TpV7C/Design-System-2.0?node-id=9%3A253
