### ISSUE TITLE
Publish Figma DS library to the latest build - Segmented Control

### ISSUE THREAD

**Issue by xinnanyemm** [MetaMask/design-tokens#328]
Continue publishing all Figma components to the latest. This task includes

Test build in sandbox
Publish
Review instances in design
Fix broken instances

**Comment by Akatori-Design** [comment]
https://www.figma.com/file/ziBXdw0BE7qIrCbTpdRIf0/Update-Banners?node-id=4701%3A19629&t=fjHrIu3N8WNftj4K-4
