### ISSUE TITLE
`BannerAlert` audit and insight report updates

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/design-tokens#330]
### Description
Complete the updates needed to align `BannerAlert` to the insight report

### Technical Details
- Rename `Banner` to `BannerAlert` 
- Add border-left previously in `BannerBase`
- Possibly more check audit and insight report in references

### Acceptance Criteria 
- `BannerAlert` meets the criteria set in the insight report

### References
- [FigJam Audit & Insight Report](https://www.figma.com/file/ZRc86y4pTE33gLMdrobHCJ/Banner-Audit?node-id=172%3A367&t=SFnUqxHYB1d14p9k-1)

**Comment by Akatori-Design** [comment]
https://www.figma.com/file/ZRc86y4pTE33gLMdrobHCJ/Banner-Audit?node-id=172%3A369&t=uaW15qQOrefo15kQ-4
