### ISSUE TITLE
Standardize icon components

### ISSUE THREAD

**Issue by Cal-L** [MetaMask/design-tokens#35]
### **Description**
Create a consistent selection of icons from the same open source library

### **Technical Details**
- If we’re using new icon set, we’ll have to buy license to icons - https://iconsax.io/ - https://lusaxweb.net/contact
- Already reached out to legal about license - pending response

### **Acceptance Criteria**
- TBD

**Comment by Cal-L** [comment]
Waiting for OK from legal for license. Work is done

**Comment by georgewrmarshall** [comment]
Duplicate #124
