### ISSUE TITLE
Review Design : Swaps Redesign 

### ISSUE THREAD

**Issue by Akatori-Design** [MetaMask/design-tokens#388]
### **Description**

Review designs for Swaps Redesign with TJ and help standardize the UI to DS norm

### **Technical Details**

- Check components, colors, text styles.
- Check design practice and consistency agianst other platforms.
- Check for any new icons, colors needed.

### **Acceptance Criteria**

- All UI elements have a reference for developers
- All missing elements are converted into work tickets

### **References**

- Figma : 
https://www.google.com/url?q=https://www.figma.com/file/CFuvr1N8sRYSTRO8kUXlan/Swaps-Extension-(Feb-%2723)?node-id%3D1040%253A71788%26t%3DXtN5vlQu0iBK2Coi-0&sa=D&source=calendar&ust=1676396045925282&usg=AOvVaw0CT8KPDPyq6jaRDDvikLiu

**Comment by xinnanyemm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Design-System-61e8a2ae77c3a60012e5003c/issues/MetaMask/design-tokens/388?planning-poker) with Zenhub @Akatori-Design @garrettbear @georgewrmarshall
