### ISSUE TITLE
Update Badge to reflect insight report

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/design-tokens#391]
### **Description**

Update Badge to reflect insight reports

### **Technical Details**
<img width="661" alt="Screenshot 2023-02-22 at 4 25 32 PM" src="https://user-images.githubusercontent.com/8112138/220786337-88d3b526-00da-4f5a-93d5-0a925b681f71.png">
<img width="632" alt="Screenshot 2023-02-22 at 4 25 44 PM" src="https://user-images.githubusercontent.com/8112138/220786359-d44642e9-5fc1-48c8-992e-7fc646e4527e.png">

### **Acceptance Criteria**

- Figma component reflects insight reports

### **References**

- [FigJam](https://www.figma.com/file/pQa2vI7r08pHiqsAPTWdQ8/Avatar%2C-Token%2C-Network%2C-Icon%2C-Badge-Audit?node-id=0%3A1&t=fedx1fSP0xZPIvat-1)

**Comment by xinnanyemm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Design-System-61e8a2ae77c3a60012e5003c/issues/MetaMask/design-tokens/391?planning-poker) with Zenhub @Akatori-Design @brianacnguyen @garrettbear
