### ISSUE TITLE
[Figma] Add news icon to Figma

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/design-tokens#402]
### **Description**

Add new icons to Figma

### **Technical Details**

- Add new svg icons to Figma
- Optimize icons using [Fontastic](https://app.fontastic.me/accounts/login/) and send to engineers

### **Acceptance Criteria**

- Figma icon name should match code
- Docs should match
- Icons should be added according to docs https://www.notion.so/Need-a-new-icon-b232f7c62a6f45bb81749cccb21904b8?pvs=4
- Optimize icons using [Fontastic](https://app.fontastic.me/accounts/login/) and send to engineers

### **References**

- Bridge icon PR in extension https://github.com/MetaMask/metamask-extension/pull/17952
- Icon docs https://www.notion.so/Need-a-new-icon-b232f7c62a6f45bb81749cccb21904b8?pvs=4
- Extension ticket https://github.com/MetaMask/metamask-extension/issues/18040
- https://github.com/MetaMask/metamask-mobile/issues/5922

**Comment by Akatori-Design** [comment]
Here's the list of the newly added icons including "bridge"
Sprite file :[https://app.zenhub.com/files/449877030/6e7409ed-8074-4930-9d4d-48dbcca6fda6/download]
cc: @georgewrmarshall 
(https://app.zenhub.com/files/449877030/6e7409ed-8074-4930-9d4d-48dbcca6fda6/download) 
![image.png](https://images.zenhubusercontent.com/62155ddebb3f5e7908734564/566f3394-9e5d-4aa4-8e6a-472c40d82ea1)

**Comment by Akatori-Design** [comment]
Sorry, I just realized we already have a Tag icon. 
Taking out the tag icon from the list. Here's the updated version.
Sprite file here :[https://app.zenhub.com/files/449877030/afff42c7-6b1a-4dc5-9c6c-56cc94988d00/download](https://app.zenhub.com/files/449877030/afff42c7-6b1a-4dc5-9c6c-56cc94988d00/download) 
cc: @georgewrmarshall 
![image.png](https://images.zenhubusercontent.com/62155ddebb3f5e7908734564/f88fbc2c-fde6-4071-a17b-6d918d058762)

**Comment by xinnanyemm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Design-System-61e8a2ae77c3a60012e5003c/issues/MetaMask/design-tokens/402?planning-poker) with Zenhub @Akatori-Design @brianacnguyen @garrettbear

**Comment by georgewrmarshall** [comment]
New sprite and screenshot in this comment https://github.com/MetaMask/metamask-mobile/issues/5922#issuecomment-1504225961
