### ISSUE TITLE
[Figma] Update Popover to reflect insight report

### ISSUE THREAD

**Issue by Akatori-Design** [MetaMask/design-tokens#405]
Update existing Popover component to eliminate discrepancy between Extension code component.

Popover (Notion) : https://www.notion.so/Popover-14c96b8934b144f6b46f5f7851923f0f?pvs=4

Popover (Storybook) : https://metamask.github.io/metamask-storybook/index.html?path=/docs/components-componentlibrary-popover--docs

**Comment by xinnanyemm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Design-System-61e8a2ae77c3a60012e5003c/issues/MetaMask/design-tokens/405?planning-poker) with Zenhub @georgewrmarshall @Akatori-Design @brianacnguyen @garrettbear
