### ISSUE TITLE
DS/2023/Q2/O1/KR2: [FIGMA] Adding a new icon

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/design-tokens#413]
### **Description**

Create a workshop and documentation materials on how to add a new icon to Figma and the process

### **Technical Details**
- What is the process?
- Who has to sign off on it?
- Naming conventions?
- SVG optimization
- TBC

### **Acceptance Criteria**
- TBC

### **References**
- TBC

**Comment by Akatori-Design** [comment]
https://www.notion.so/Need-a-new-icon-b232f7c62a6f45bb81749cccb21904b8?pvs=4

**Comment by Akatori-Design** [comment]
https://www.notion.so/Need-a-new-icon-b232f7c62a6f45bb81749cccb21904b8
