### ISSUE TITLE
[Figma] Update Modal component to reflect insight report

### ISSUE THREAD

**Issue by Akatori-Design** [MetaMask/design-tokens#417]

**Comment by xinnanyemm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Design-System-61e8a2ae77c3a60012e5003c/issues/MetaMask/design-tokens/417?planning-poker) with Zenhub @Akatori-Design @brianacnguyen @garrettbear

**Comment by Akatori-Design** [comment]
https://www.figma.com/file/HKpPKij9V3TpsyMV1TpV7C/DS-Components?node-id=15111-39125&t=5qoiErmNL8iOfPY8-4

Will update against the storybook and review again once @georgewrmarshall is done building in code.
