### ISSUE TITLE
[Figma] Create Modal design doc

### ISSUE THREAD

**Issue by Akatori-Design** [MetaMask/design-tokens#441]
- Create design doc for `Modal`

Include:
- When to use
- Usage Guideline
- Best Practices
- Accessibility
- Ext / Mob links

Publish to Notion design doc
https://southern-bush-399.notion.site/Metamask-Design-System-f86ecc914d6b4eb6873a122b83c12940

**Comment by xinnanyemm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Design-System-61e8a2ae77c3a60012e5003c/issues/MetaMask/design-tokens/441?planning-poker) with Zenhub @Akatori-Design @brianacnguyen @garrettbear

**Comment by Akatori-Design** [comment]
Added what I have so far to Notion & Figma
https://www.notion.so/Modal-1c358986fac74bdd84494473f992256f?pvs=4
