### ISSUE TITLE
[Figma] Update BottomSheet to reflect insight reports update

### ISSUE THREAD

**Issue by Akatori-Design** [MetaMask/design-tokens#444]
Update BottomSheet to reflect insight reports update

- Create new `Bottom Sheet` to match new updates in insight reports
- Deprecate old `Sheet` figma component

**Comment by xinnanyemm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Design-System-61e8a2ae77c3a60012e5003c/issues/MetaMask/design-tokens/444?planning-poker) with Zenhub @Akatori-Design @brianacnguyen @garrettbear
