### ISSUE TITLE
[DESIGN] Update Tooltip to reflect insight report

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/design-tokens#447]
### Description
Update Tooltip component in Figma to reflect insight report

### Technical Details
- Update component name to match insight report
- Update component description to match insight report
- Update component variants to match insight report

### Acceptance Criteria
- Component name matches insight report 
- Component description matches insight report 
- Component variants match insight report

**Comment by Akatori-Design** [comment]
@georgewrmarshall Can we delete this and recreate a new one after we finish the Tooltip  insight reports?

**Comment by georgewrmarshall** [comment]
Yes, you can close. If you don't mind creating in future
<img width="1009" alt="Screenshot 2023-09-11 at 7 50 30 PM" src="https://github.com/MetaMask/design-tokens/assets/8112138/947db90f-cb86-4105-8406-f18e76d25722">
