### ISSUE TITLE
[Figma] Update Textarea to match insight report

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/design-tokens#450]
### Description
Update Textarea component in Figma to reflect insight report

### Technical Details
- Update component name to match insight report
- Update component description to match insight report
- Update component variants to match insight report

### Acceptance Criteria
- Component name matches insight report 
- Component description matches insight report 
- Component variants match insight report

**Comment by Akatori-Design** [comment]
@georgewrmarshall Can we delete this and recreate a new one after we finish the Text Area audit &  insight reports?

**Comment by georgewrmarshall** [comment]
I think there is value in keeping it open
