### ISSUE TITLE
Introduction to the Extension component-library

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/design-tokens#451]
### Description
Create an educational video to introduce the extension component-library

### Technical Details
https://www.notion.so/Extension-component-library-7dc2115bfcf74a7db37cd322f231e675?pvs=4

### Acceptance Criteria
- After watching an engineer should be able to effectively and efficiently use the component-library in the extension

**Comment by xinnanyemm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Design-System-61e8a2ae77c3a60012e5003c/issues/MetaMask/design-tokens/451?planning-poker) with Zenhub @Akatori-Design @brianacnguyen @garrettbear

**Comment by georgewrmarshall** [comment]
This has been completed and can be found here
https://www.notion.so/Extension-Engineer-8da34c7887fe4f2182305a5d576d199c?pvs=4


https://user-images.githubusercontent.com/8112138/236995848-302dffaa-4180-4508-aa1f-4e414ac956c7.mov
