### ISSUE TITLE
[Figma] Create Dropdown component 

### ISSUE THREAD

**Issue by Akatori-Design** [MetaMask/design-tokens#461]
- Create Dropdown component.

**Comment by georgewrmarshall** [comment]
Should we create audit and insight report tickets for this component?

**Comment by Akatori-Design** [comment]
This ticket is for creating Picker Pill in Figma as a generic component to support Picker Network, but the audit file will be shared with the [Picker/Select Audit file](https://www.figma.com/file/ARJUQovVqX6QkGgiIpPOD3/Picker%2FSelect-Audit?type=whiteboard&node-id=0%3A1&t=7RyO5nc7QZeiA0lf-1)

**Comment by georgewrmarshall** [comment]
Ah yes of course, my bad!
