### ISSUE TITLE
[Figma] Sepolia not available in Avatar component as badge

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/design-tokens#481]
### **Description**

Sepolia doesn't seem to be available as a badge in avatar

https://github.com/MetaMask/design-tokens/assets/8112138/810dfd66-aaf3-4494-add7-89e93b6bad0e

### **Technical Details**

- Update so Sepolia is available 

### **Acceptance Criteria**

- Sepolia is an available variant on the Avatar component as a badge option

**Comment by Akatori-Design** [comment]
Added & published update.
<img width="876" alt="image" src="https://github.com/MetaMask/design-tokens/assets/55973039/48387a52-07d2-40e7-bba1-29a29d647c99">

**Comment by georgewrmarshall** [comment]
Nice one
