### ISSUE TITLE
Shadow styles

### ISSUE THREAD

**Issue by SaraCheikh** [MetaMask/design-tokens#55]
### **Description**

Standarize the shadows we use in the product (Documentation)

### **Technical Details**

-Create shadow styles for all the backgrounds we are using 

### **References**

-Figma link: https://www.figma.com/file/HKpPKij9V3TpsyMV1TpV7C/Design-System-2.0?node-id=1049%3A8020

**Comment by georgewrmarshall** [comment]
completed
