### ISSUE TITLE
Color V1 : Deprecating unused/unsupported colors

### ISSUE THREAD

**Issue by Akatori-Design** [MetaMask/design-tokens#59]
### **Description**

Describe the task. What does this aim to solve?

Today, 1/3 of our color tokens (v1) are either unused or will be unused.
These colors need to be deprecated and removed from the color list so design & dev will discontinue to use.

- Remove tokens in codebase.
- Update Figma color file.

### **Acceptance Criteria**

- Color listed in below figma link are removed from codebase.
- Any UI elements that lose color reference should be recitified. (How? Make it a component token)
- Color listed in below figma link are removed from Figma doc & library.

### **References**

- https://www.figma.com/file/kdFzEC7xzSNw7cXteqgzDW/%5BColor%5D-Light-Theme?node-id=693%3A543
![image.png](https://images.zenhubusercontent.com/62155ddebb3f5e7908734564/76670b35-4287-4d2b-8a82-376418d24b02)

**Comment by georgewrmarshall** [comment]
https://github.com/MetaMask/design-tokens/pull/86
