### ISSUE TITLE
Publish design token NPM package

### ISSUE THREAD

**Issue by Cal-L** [MetaMask/design-tokens#6]
@Cal-L commented on [Tue Jan 18 2022](https://github.com/MetaMask/metamask-mobile/issues/3602)

# Description
- Publish design token package that will be utilized by both extension and mobile component systems

# Technical Details
- Publish design token package (do manually for now)
- Package can be named under something like `@metamask/design-tokens`

# Acceptance Criteria
- Published package should be added as a dependency in package.json
- Ability to utilize design tokens in component system

**Comment by georgewrmarshall** [comment]
Done!
