### ISSUE TITLE
Improve TypeScript exports for JS tokens

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/design-tokens#611]
### Description
Currently, the mobile project is importing types from the design tokens by traversing into the source folder. This is not ideal and could be improved by exporting all types from `@metamask/design-tokens/types`. This change would enhance the developer experience.

### Technical Details
- Export all types from the root `index.ts`

### Acceptance Criteria
- All types are exported from `@metamask/design-tokens/types`.
- The mobile project can import types directly from `@metamask/design-tokens/types` without traversing into the source folder.

### Additional Information
Once the types are correctly exported, the change should be tested in the mobile project to ensure it works as expected.

**Comment by hilvmason** [comment]
revisit this issue, may need to break down further
this ticket needs a follow up ticket to update the imports in mobile
