### ISSUE TITLE
Flask purple needs to be reviewed and discussed with adding to the design token colors

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/design-tokens#63]
### **Description**

Need to review whether the --flask-purple: #8b45b6 should be added to the design tokens. IMO it is one of the MetaMask brand colors so it should be.

### **Technical Details**
TBC

### **Acceptance Criteria**
TBC

### **References**

[ExperimentalArea](https://metamask.github.io/metamask-storybook/index.html?path=/story/ui-components-app-flask-experimental-area-experimental-area-stories-js--default-story)

**Comment by Akatori-Design** [comment]
@georgewrmarshall 
So looking at Flash extension, I don't see any use of this purple in the UI today, which is kinda sad😞
For Flask, is the future plan to replace the primary-blue with the purple (as in the promo video)?

**Comment by georgewrmarshall** [comment]
@holantonela might be able to answer this better than me :)

**Comment by georgewrmarshall** [comment]
Completed
