### ISSUE TITLE
[EXT, MOBILE] Introduce shadows into design tokens library

### ISSUE THREAD

**Issue by Cal-L** [MetaMask/design-tokens#64]
### **Description**

Introduce shadows into design system library

### **Technical Details**

- Add shadow data structure to @metamask/design-system library
- Publish with new version of design system library

### **Acceptance Criteria**

- Codebase should be able to access shadow properties
- Shadow properties from code should match that of Figma

### **References**

- Figma shadow doc - https://www.figma.com/file/HKpPKij9V3TpsyMV1TpV7C/Design-System-2.0?node-id=1049%3A8020

**Comment by georgewrmarshall** [comment]
complete
