### ISSUE TITLE
[PORT] Test Brand Evolution Design Token Updates in Pre-Release Branch

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/design-tokens#653]
### Description

As part of our ongoing efforts to align our portfolio with the latest brand evolution standards, we have introduced a series of design token updates reflecting brand evolution. Before these changes are merged into the main branch and become part of our official release, it is crucial to conduct thorough testing in a pre-release branch. This testing aims to ensure that the design token updates integrate seamlessly with existing components and features, maintaining or enhancing the overall user experience without introducing regressions.

### Technical Details

- **Objective**: Conduct comprehensive testing of the brand evolution design token updates within a designated pre-release branch of the portfolio.
- **Scope**: The testing should cover all aspects of the portfolio affected by the design token updates, including but not limited to UI components, layout, and theming.
- **Testing Branch**: The updates are available in the `pre-release-brand-evolution` branch (name subject to change based on the actual branch used).
- **Key Areas for Testing**:
  1. Visual consistency with the new brand guidelines.
  2. Compatibility of design token updates with existing components.

### Acceptance Criteria

- All key components and features within the portfolio accurately reflect the updated design tokens, adhering to the new brand guidelines.
- No visual regressions or inconsistencies are introduced as a result of the design token updates.
- Stakeholder feedback (from design, product, and engineering teams) on the pre-release branch is overwhelmingly positive, with any concerns adequately addressed.
- Works in light and dark themes

### Additional Notes

This testing phase is a critical step in our brand evolution journey, ensuring that our portfolio not only aligns with our new brand identity but also continues to deliver an exceptional user experience. Collaboration and open communication among all team members will be key to identifying and resolving any issues that arise during testing.

### Tracking

Progress on this testing initiative will be tracked through this GitHub issue, with updates and findings documented as comments or linked documents. Stakeholders are encouraged to provide feedback directly within this issue or through designated communication channels.

**Comment by georgewrmarshall** [comment]
Logged out dark mode


https://github.com/MetaMask/design-tokens/assets/8112138/25e2484e-51b8-44f1-bd53-103013ec7652

**Comment by georgewrmarshall** [comment]
Logged out light theme


https://github.com/MetaMask/design-tokens/assets/8112138/0220a909-8da5-4c4e-9c75-0ffddcd92f59

**Comment by georgewrmarshall** [comment]
Tested and looks good

**Comment by georgewrmarshall** [comment]
Checked for any console errors regarding design token update are not present. Although portfolio does seem to have a few console errors

<img width="1509" alt="Screenshot 2024-06-11 at 1 39 12 PM" src="https://github.com/MetaMask/design-tokens/assets/8112138/8b9e10ba-477a-470e-8e67-4dfee9bb807e">
<img width="1512" alt="Screenshot 2024-06-11 at 1 39 30 PM" src="https://github.com/MetaMask/design-tokens/assets/8112138/dedc4c4c-33da-490a-89eb-89b4d67350ec">

**Comment by garrettbear** [comment]
Approve 👍

**Comment by Akatori-Design** [comment]
Approve 🙌  Lookin nice!

**Comment by georgewrmarshall** [comment]
Here is the branch and test build https://github.com/consensys-vertical-apps/metamask-portfolio/pull/818
