### ISSUE TITLE
[EXT] Test Design Token Updates in Pre-Release Branch for Extension

### ISSUE THREAD

**Issue by garrettbear** [MetaMask/design-tokens#655]
### Description
The purpose of this ticket is to ensure that the recent updates to the design tokens, as part of our brand evolution, are correctly implemented and functioning as expected in the portfolio's pre-release branch. This involves a comprehensive testing phase to identify any discrepancies, visual or functional, that may arise from the new design token updates.

### Technical Details
- The updates are located in the `feature/brand-evolution-design-tokens` branch.
- Testing should cover all major components affected by design tokens, including typography, color schemes, button styles, and layout spacings.
- Use both automated and manual testing strategies to cover a wide range of scenarios.
- Ensure compatibility across all supported browsers and devices.
- Any found issues should be documented with screenshots and detailed descriptions.

### Acceptance Criteria
1. All major components (e.g., headers, footers, buttons, input fields) reflect the updated design tokens correctly.
2. The application maintains its responsiveness and functionality across different screen sizes and devices.
3. No visual regressions are introduced by the design token updates.
4. The application is tested across all supported browsers (Chrome, Firefox, Safari, Edge) with no compatibility issues.
5. All discovered issues are documented and reported in the GitHub repository with appropriate labels.
6. Pair with Hiro to walk through designs together to determine acceptance from design

**Comment by garrettbear** [comment]
PR: https://github.com/MetaMask/metamask-extension/pull/25268
Storybook: https://output.circle-artifacts.com/output/job/73c987ab-ee77-42f1-a5ca-5645595f007c/artifacts/0/storybook/index.html?path=/story/components-componentlibrary-button--variant
Build: https://github.com/MetaMask/metamask-extension/pull/25268#issuecomment-2164030149

No errors related to design system
<img width="1480" alt="Screenshot 2024-06-13 at 9 58 18 AM" src="https://github.com/MetaMask/design-tokens/assets/26469696/ea7e03b9-c3ae-4d45-b80e-0b94065603ba">

**Comment by georgewrmarshall** [comment]
There are a couple instances that use the JS tokens, so they haven't been updated in this branch

![Screenshot 2024-06-13 at 3 06 30 PM](https://github.com/MetaMask/metamask-extension/assets/8112138/a8c723ef-bcee-4b4e-870d-74a739de2d04)

https://github.com/MetaMask/metamask-extension/blob/0c02dd51b767ffc1a745d962fdf7ee6f204d8330/ui/components/ui/toggle-button/toggle-button.component.js#L42-L43

**Comment by garrettbear** [comment]
Yes I cover that in my video, sorry you beat me before I could get the video loaded 
@georgewrmarshall

**Comment by garrettbear** [comment]
https://github.com/MetaMask/design-tokens/assets/26469696/497a9ae0-e227-4eb2-9291-478b9cd991cd

**Comment by garrettbear** [comment]
This video is using yarn link so it includes the JS and CSS (toggle button uses JS) 

https://github.com/MetaMask/design-tokens/assets/26469696/7a7d0ca2-f174-414b-94cc-992a4ea3f3f9

**Comment by garrettbear** [comment]
> There are a couple instances that use the JS tokens, so they haven't been updated in the test build
> 
> ![Screenshot 2024-06-13 at 3 06 30 PM](https://private-user-images.githubusercontent.com/8112138/339566764-a8c723ef-bcee-4b4e-870d-74a739de2d04.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzMTY5OTQsIm5iZiI6MTcxODMxNjY5NCwicGF0aCI6Ii84MTEyMTM4LzMzOTU2Njc2NC1hOGM3MjNlZi1iY2VlLTRiNGUtODcwZC03NGE3MzlkZTJkMDQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTNUMjIxMTM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzZiYjkxYTJlODRkNWFkMDYzOGY4YjczZTNkZmIzMzEzYTY5N2MzOGFlNDY2ZDNmNTcyZTE2NzY5Nzk0NmJlYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.dcSdtN-gRYIq5kJWxmAF19EyCcbbr3DyAa3ULVJpMWk)
> 
> https://github.com/MetaMask/metamask-extension/blob/0c02dd51b767ffc1a745d962fdf7ee6f204d8330/ui/components/ui/toggle-button/toggle-button.component.js#L42-L43

<img width="240" alt="Screenshot 2024-06-13 at 4 15 53 PM" src="https://github.com/MetaMask/design-tokens/assets/26469696/3c054d00-b551-429d-aae9-1c5b10310a6f">
using yarn link

**Comment by georgewrmarshall** [comment]
Excellent videos LGTM!

**Comment by Akatori-Design** [comment]
Look good. I Approve

**Comment by brianacnguyen** [comment]
LGTM
