### ISSUE TITLE
Update CSS-in-JS with Brand Color Tokens - Dark Theme

### ISSUE THREAD

**Issue by garrettbear** [MetaMask/design-tokens#661]
Create new brand colors
Deprecate old tokens that no longer exists blue000, 
Waiting on white/black for clarification we will need these
Add comments to types to show hex values in VScode look at src/js/brandColor/brandColor.types.ts
Start with brandColors to use within light/dark theme
Double check storybook docs working

**Comment by georgewrmarshall** [comment]
This has been completed https://github.com/MetaMask/design-tokens/pull/692
