### ISSUE TITLE
[PS UI] Componentize Account Element

### ISSUE THREAD

**Issue by Cal-L** [MetaMask/design-tokens#68]
### **Description**

Componentize Account Element on Permission System in Figma

### **Technical Details**

- Componentize Account Element component
- Use DS rules, colors, spacing, typography
- Original PS UI should use this component

### **Acceptance Criteria**

- Component should be identifiable in Figma
- Original PS UI should use this component

### **References**

- Original Figma - https://www.figma.com/file/LRpO3E6SFcNs6KXCfolwyM/Permissions-System---Intermediate-Design?node-id=51%3A2641
- DS component Figma - 
https://www.figma.com/file/HKpPKij9V3TpsyMV1TpV7C/Design-System-2.0?node-id=11%3A9

**Comment by georgewrmarshall** [comment]
Related to #54
