### ISSUE TITLE
[PS UI] Componentize Network Switcher

### ISSUE THREAD

**Issue by Cal-L** [MetaMask/design-tokens#69]
### **Description**

Componentize Network Switcher on Permission System in Figma

### **Technical Details**

- Componentize Network Switcher component
- Use DS rules, colors, spacing, typography
- Original PS UI should use this component

### **Acceptance Criteria**

- Component should be identifiable in Figma
- Original PS UI should use this component

### **References**

- Figma - https://www.figma.com/file/LRpO3E6SFcNs6KXCfolwyM/Permissions-System---Intermediate-Design?node-id=51%3A2641

**Comment by Akatori-Design** [comment]
@SaraCheikh I'll work on this ticket
