### ISSUE TITLE
[PS UI] Componentize Avatar Element

### ISSUE THREAD

**Issue by Cal-L** [MetaMask/design-tokens#70]
### **Description**

Componentize  Avatar Element on Permission System in Figma

### **Technical Details**

- Componentize  Avatar Element component
- Use DS rules, colors, spacing, typography
- Original PS UI should use this component

### **Acceptance Criteria**

- Component should be identifiable in Figma
- Original PS UI should use this component

### **References**

- Figma - https://www.figma.com/file/HKpPKij9V3TpsyMV1TpV7C/Design-System-2.0?node-id=1614%3A12084

**Comment by Cal-L** [comment]
This component lives in https://github.com/MetaMask/design-tokens/issues/54

**Comment by Akatori-Design** [comment]
@SaraCheikh  I'll take over this ticket. Separating Avatar from Icon.

**Comment by SaraCheikh** [comment]
In the variants there is actually a type only for avatar without the icon

**Comment by georgewrmarshall** [comment]
Related Figma Links
- https://www.figma.com/file/HKpPKij9V3TpsyMV1TpV7C/Design-System-2.0?node-id=1614%3A12085
- https://www.figma.com/file/HKpPKij9V3TpsyMV1TpV7C/Design-System-2.0?node-id=1053%3A8526
