### ISSUE TITLE
[FIGMA] Animation Tokens (Audit Animation Tokens in Code + Documenting in Figma)

### ISSUE THREAD

**Issue by justincheungcon** [MetaMask/design-tokens#701]
**Description**

- We have too many animation tokens, and not enough consistency with how we animate components in our experience

**Key Results**

- [ ] Have 4 clear animation tokens with new, intuitive names for animation tokens. 
- [ ] Have a plan to implement this in code
- [ ] Merge branch into main file

Figma: 
https://www.figma.com/design/HKpPKij9V3TpsyMV1TpV7C/branch/9NhaNoEBAjLTpCapO6HtaJ/DS-Components?node-id=27125-10051&t=3lqAyuGSGWYkK2kI-11

Figma audit and insight report https://www.figma.com/board/YgiKBnoHYl3dLVEYqwjMcA/Animations-Audit-and-Insight-Report?node-id=0%3A1&t=wWSL9GX57sOHcheZ-1

**Comment by Akatori-Design** [comment]
Is this the dev ticket or design ticket?
