### ISSUE TITLE
Update js variables based on updated json on brand evolution branch

### ISSUE THREAD

**Issue by brianacnguyen** [MetaMask/design-tokens#713]
Update js variables based on updated json
- Also update tests

**Comment by georgewrmarshall** [comment]
Completed in these commits
- https://github.com/MetaMask/design-tokens/pull/692/commits/559ed13697ece7b2c1baf8b7f5faa8e7e34647b8
- https://github.com/MetaMask/design-tokens/pull/692/commits/79214f9e8ebdda1c6784da4b5dfaa114aa798ca6
