### ISSUE TITLE
[PORT] Update design-tokens package to version 4.0.0

### ISSUE THREAD

**Issue by brianacnguyen** [MetaMask/design-tokens#714]

**Comment by georgewrmarshall** [comment]
PR here: https://github.com/consensys-vertical-apps/metamask-portfolio/pull/772

**Comment by georgewrmarshall** [comment]
PR above ready for review @brianacnguyen

**Comment by georgewrmarshall** [comment]
This has been completed in https://github.com/consensys-vertical-apps/metamask-portfolio/pull/772
